import { SeededRng } from "./prng.js";
import { type GameConfig, CURVE_AMPLITUDE, CURVE_BASE_RATE } from "./config.js";
import type { Tick } from "./types.js";

/**
 * Authoritative shared price curve.
 *
 * Generated by band-limited Fourier synthesis: a fixed number of sinusoids whose
 * frequencies, amplitudes and phases are derived deterministically from the daily
 * server seed. The raw sum is passed through tanh for bounding and a small additive
 * bias for green dominance. Both sin(...) and tanh(...) are C-infinity (infinitely
 * differentiable), so the curve has continuous derivatives of every order — it is
 * mathematically impossible for it to contain a pointed peak (a C0 cusp).
 *
 * Determinism: value(t) depends only on (serverSeed, t), so every connected client
 * renders an identical curve and outcomes are reproducible/verifiable.
 */
export interface CurveComponent { freq: number; amp: number; phase: number; }

export class CurveGenerator {
  readonly components: CurveComponent[];
  private readonly ampNorm: number;

  constructor(serverSeed: string, private readonly cfg: GameConfig, private readonly K = 6) {
    const rng = new SeededRng(serverSeed, "curve");
    const baseFreq = 0.06;  // Hz — base swell (~17s period); higher = faster wave
    const ratio = 1.9;      // geometric spread across octaves
    const comps: CurveComponent[] = [];
    let ampSum = 0;
    for (let k = 0; k < K; k++) {
      const freq = baseFreq * ratio ** k;
      // pink-ish 1/f^0.9 amplitude with mild per-component jitter
      const amp = (1 / freq ** 0.9) * rng.range(0.85, 1.15);
      ampSum += amp;
      comps.push({ freq, amp, phase: rng.range(0, 2 * Math.PI) });
    }
    this.components = comps;
    this.ampNorm = ampSum; // normalise so the pre-tanh sum is ~O(1)
  }

  /** Smooth signal in (-1, 1). t is seconds. */
  value(t: number): number {
    let s = 0;
    for (const c of this.components) s += c.amp * Math.sin(2 * Math.PI * c.freq * t + c.phase);
    s /= this.ampNorm;
    // green dominance: small positive additive bias before the smooth squash
    const biased = s * this.cfg.volatility + this.cfg.driftBias;
    return Math.tanh(biased);
  }

  /** Displayed rate, centred at `base`. */
  rate(t: number, base = CURVE_BASE_RATE): number {
    return base + CURVE_AMPLITUDE * this.value(t);
  }

  /** Build a tick at epoch ms relative to the day-start epoch ms. */
  tick(nowMs: number, dayStartMs: number, prevRate?: number): Tick {
    const t = (nowMs - dayStartMs) / 1000;
    const rate = this.rate(t);
    return { t: nowMs, rate, delta: prevRate === undefined ? 0 : rate - prevRate };
  }
}
